# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08a6c4884a6fb5c24dfdaa010394ce3a56528e9d47cb1a1080202481b6e40f7e419d3445b5a13e2a4a495d52b9b8ad1e8770d912e9f4314dbb446ae006beaf93

test:
  secret_key_base: f5aa0803677aa936cb28d04dd11cc5050090c5eb6d3e8fbe109ae3ddeb9f7036c5b4a7fe7f3c5a1f3bca417dbb5febdb63afb08bb163c3c5230dc2e1ddb403d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
